Attack <- read.csv("Attack.csv")
Attack$Starttime <- as.POSIXct(Attack$Start.time, origin="1970-01-01")
Attack$Lasttime <- as.POSIXct(Attack$Last.time, origin="1970-01-01")
plot(Attack$Starttime)
plot(Attack$Lasttime)
Attack$Category <- as.factor(Attack$Attack.category)
Attack$Subcategory <- as.factor(Attack$Attack.subcategory)
plot(Attack$Category)
plot(Attack$Subcategory)
Attack$Protocolos <- as.factor(Attack$Protocol)
plot(Attack$Protocolos)
Attack$Referencias <- as.factor(Attack$Attack.Reference)
plot(Attack$Referencias)

